### ISSUE TITLE
Show latest Raspberry Pi releases

### ISSUE THREAD

**Issue by patricktokeeffe** [ubuntu-mate/ubuntu-mate.org#23]
I'm a little confused as to why <https://ubuntu-mate.org/download/> only shows 16.04.2 (Xenial) under Raspberry Pi releases:

![2018_10_03_13_26_28_download_ubuntu_mate](https://user-images.githubusercontent.com/1348834/46445480-f3a50700-c72b-11e8-91d4-c17ba4c58dda.png)

Choosing other architectures produces newer releases. And when I login to a fresh Xenial install on Raspberry Pi 3, I'm told a newer version is available (18.04.1 LTS):
```
Welcome to Ubuntu 16.04.2 LTS (GNU/Linux 4.4.38-v7+ armv7l)

 * Documentation:  https://help.ubuntu.com
 * Management:     https://landscape.canonical.com
 * Support:        https://ubuntu.com/advantage

0 packages can be updated.
0 updates are security updates.

New release '18.04.1 LTS' available.
Run 'do-release-upgrade' to upgrade to it.

Last login: Wed Oct  3 16:43:44 2018
lar@dmz:~$
```

But I see <http://cdimage.ubuntu.com/ubuntu-mate/releases/18.04/release/> doesn't list `armhf` releases yet. Is this a case of the release being out, but images haven't been built? (*I only ask because it's not possible to dist-upgrade a Raspberry Pi from 16.04 - the boot partition is too small.*)

**Comment by lah7** [comment]
Unlike the desktop builds, images for the Raspberry Pi are not built on Canonical's architecture, so they won't appear on http://cdimage.ubuntu.com. However, since these builds use the official Ubuntu `armhf` repositories, the Pi may behave like desktop Ubuntu in that it sees newer versions available.

The Ubuntu MATE team (specifically @flexiondotorg) generates and tests Raspberry Pi builds separately to the main project, but there has been a slight delay for 18.04. There hasn't been any newer 16.04 images built since 16.04.2 either.

**Comment by patricktokeeffe** [comment]
OK, great info, thank you!
