### ISSUE TITLE
[Suggestion] New banner design

### ISSUE THREAD

**Issue by mikeroyal** [ubuntu-mate/ubuntu-mate.org#29]
I was thinking the gray banner on the Ubuntu MATE site could get a simple redesign to make the MATE logo and text really pop. Basically, take the existing grey banner and give it a dark theme look. I made a rough render what it would look like.

Current design
![mate-site](https://user-images.githubusercontent.com/45159366/56716965-70132d80-66f0-11e9-813d-1c1126a24874.png)

New design
![mate-site1](https://user-images.githubusercontent.com/45159366/56716969-71445a80-66f0-11e9-847b-2dc9c1fbb732.png)

**Comment by lah7** [comment]
Thanks for your suggestion. We're in the process of re-developing the site, so we will keep the contrast in mind for the banner. 

A condensed font seems out of place with the rest of Ubuntu MATE (on the desktop and the web), plus it would be desirable to keep the triangle backdrop as a symbolic reference to the [Ubuntu] MATE logo.

_:bulb: Did you notice the triangles also randomise each time? That'll likely be dropped in future for various reasons, but this was an intentional nod to MATE's vast customisation - no desktop/panel may look the same._

---

So, based on your suggestion, I think we'll lower the backdrop contrast to deliver that "pop". :+1:

**Comment by lah7** [comment]
Thanks again for the suggestion last year. We just launched a new website update with a refreshed design. For the banner, we didn't go the dark route - instead, we like the greenness of the triangles wallpaper.
