### ISSUE TITLE
Ubuntu Mate 18.04 for the Raspberry Pi

### ISSUE THREAD

**Issue by swinterbotix** [ubuntu-mate/ubuntu-mate.org#81]
Hi,

I noticed that you are advertising Ubuntu Mate 18.04.4 on your website for the Pi, but the link ends up downloading Ubuntu Mate 18.04.2. Should this be updated?

**Comment by lah7** [comment]
Thanks for the report, this has been corrected.

From the site's perspective, this happened because the [metadata for downloads](https://github.com/ubuntu-mate/ubuntu-mate.org/blob/master/_data/downloads.yml) has been sharing the same release information. This can now be overridden, so it won't say 18.04.4 for the Raspberry Pi when 18.04.2 is the only download available. 

I'm not aware of any plans to generate newer point release images.
